@RecipeBox_BaseURL = http://0.0.0.0:5073/api

###

GET {{RecipeBox_BaseURL}}/recipes/
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Accept: application/json

###

GET {{RecipeBox_BaseURL}}/recipes/1
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Accept: application/json

###

POST {{RecipeBox_BaseURL}}/register/
Content-Type: application/json

{
  "email": "me@example.com",
  "password": "P@ssword1"
}

###


# @name loginRequest
POST {{RecipeBox_BaseURL}}/login/
Content-Type: application/json

{
  "email": "me@example.com",
  "password": "P@ssword1"
}

###

GET {{RecipeBox_BaseURL}}/me/
Authorization: Bearer {{loginRequest.response.body.accessToken}}

###

POST {{RecipeBox_BaseURL}}/recipes/
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Content-Type: application/json

{
    "name": "Buffalo Chicken Pizza",
    "ingredients": "Mozzerella\nPizza crust\n\nBuffalo sauce\nChicken",
    "directions": "Put ingredients on pizza crust and bake at 400 degrees for 10 minutes."
}

###

PUT {{RecipeBox_BaseURL}}/recipes/5
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Content-Type: application/json

{
    "name": "Buffalo Chicken Pizza",
    "ingredients": "Mozzerella\nPizza crust\n\nBuffalo sauce\nChicken",
    "directions": "Put ingredients on pizza crust and bake at 400 degrees for 10 minutes."
}
